# Generated by Django 5.0.7 on 2024-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ngo_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'Charity',
                'verbose_name_plural': 'Charities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PledgeOrganizations',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
