# Generated by Django 5.0.7 on 2024-08-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['name'], 'verbose_name': 'Charity', 'verbose_name_plural': 'Charities'},
        ),
    ]
