# Generated by Django 5.0.7 on 2024-11-20 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg'])])),
                ('color', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Cause',
                'verbose_name_plural': 'Causes',
            },
        ),
    ]
