# Generated by Django 5.0.7 on 2024-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causes',
            options={'verbose_name': 'Cause', 'verbose_name_plural': 'Causes'},
        ),
        migrations.AlterModelOptions(
            name='membercause',
            options={'verbose_name': 'Member Cause', 'verbose_name_plural': 'Member Causes'},
        ),
        migrations.AlterField(
            model_name='causes',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
