# Generated by Django 5.0.7 on 2024-08-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_alter_causes_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberCause',
        ),
    ]
