# Generated by Django 5.0.7 on 2024-11-21 11:39

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Giving Style',
                'verbose_name_plural': 'Giving Styles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/dxeogv8rj/image/upload/v1732121946/media/images/upload.svg', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='giving_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giving_style', to='givers.givingstyle'),
        ),
    ]
