# Generated by Django 5.0.7 on 2024-08-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ngo_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='giving_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together={('user', 'skill')},
        ),
        migrations.CreateModel(
            name='UserCharitySupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_date', models.DateField()),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='givers.charity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='givers.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='supported_charities',
            field=models.ManyToManyField(through='givers.UserCharitySupport', to='givers.charity'),
        ),
        migrations.DeleteModel(
            name='UserCharity',
        ),
    ]
