# Generated by Django 5.0.7 on 2024-08-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0002_charity_alter_user_about_me_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharitysupport',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.charity'),
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='userskills',
            options={'ordering': ['user']},
        ),
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='supported_charities',
            field=models.ManyToManyField(through='givers.UserCharitySupport', to='organizations.charity'),
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='skill',
        ),
        migrations.AddField(
            model_name='userskills',
            name='skill',
            field=models.ManyToManyField(to='givers.skill'),
        ),
    ]
