# Generated by Django 5.0.7 on 2024-08-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0002_alter_skill_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
