# Generated by Django 5.0.7 on 2024-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0003_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
