# Generated by Django 5.0.7 on 2024-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0003_alter_usercharitysupport_charity_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_terms',
            field=models.BooleanField(default=True),
        ),
    ]
