# Generated by Django 5.0.7 on 2024-08-23 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_delete_membercause'),
        ('givers', '0005_alter_usercharitysupport_support_date_and_more'),
        ('organizations', '0003_pledgeorganizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userspledgeorganizations',
            name='pledge_organization',
        ),
        migrations.CreateModel(
            name='UserCauses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.ManyToManyField(to='causes.causes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Cause',
                'verbose_name_plural': 'Member Causes',
            },
        ),
        migrations.AddField(
            model_name='userskills',
            name='skill',
            field=models.ManyToManyField(to='givers.skill'),
        ),
        migrations.AddField(
            model_name='userspledgeorganizations',
            name='pledge_organization',
            field=models.ManyToManyField(to='organizations.pledgeorganizations'),
        ),
    ]
