# Generated by Django 5.0.7 on 2024-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='United States', max_length=128),
        ),
    ]
