# Generated by Django 5.0.7 on 2024-08-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0006_remove_userskills_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercauses',
            options={'ordering': ['user'], 'verbose_name': 'User Cause', 'verbose_name_plural': 'User Causes'},
        ),
        migrations.AlterModelOptions(
            name='userscharityownevent',
            options={'ordering': ['user'], 'verbose_name': 'User Own Event', 'verbose_name_plural': 'User Own Events'},
        ),
        migrations.AlterField(
            model_name='usercauses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_causes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userscharityownevent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userspledgeorganizations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pledge_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
