# Generated by Django 5.0.7 on 2024-09-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0007_alter_usercauses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='icons/upload.svg', upload_to='images/'),
        ),
    ]
