# Generated by Django 5.0.7 on 2024-09-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0010_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(default='images/upload.svg', upload_to='images/'),
        ),
    ]
