# Generated by Django 5.0.7 on 2024-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0011_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, default='images/upload.svg', null=True, upload_to='images/'),
        ),
    ]
