# Generated by Django 5.0.7 on 2024-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0012_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscharityownevent',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
